- content/circonus/on-premises/changelog/2020.md
Duplicate data_storage entries from the 2020-04-20 release.
> Remove some duplicate entries

- content/circonus/on-premises/installation/installation.md
- static/css/custom.css
The rendered output is more pleasant to read (IMO) and semantically rich due to the use of the `<dl>` element.
> CIRC-5034 Use definition lists for site.json reference

- content/circonus/on-premises/installation/getting-started.md
- content/circonus/on-premises/installation/installation.md
- content/circonus/on-premises/installation/upgrading.md
- content/circonus/on-premises/roles-services/broker.md
- content/circonus/on-premises/roles-services/data-storage.md
- content/circonus/on-premises/troubleshooting.md
Also remove the section on NNT condensing, since everyone is on NNTBS
now.
> CIRC-5093 Remove OmniOS from Inside manual

- content/circonus/agents/circonus-logwatch.md
Add in docs for logwatch such that prospects only need to go to one place.
> CIRC-5212 Add in docs for logwatch

- content/circonus/administration/account-settings.md
Rename Account Profile to Account Settings. This page otherwise needs a
lot of work, but at least the page won't display when someone searches
for "profile"
> CIRC-5220 Rename Account Profile to Account Settings

- content/circonus/administration/enterprise-brokers.md
Move the rebuild process into the Reinstallation section where it belongs.
It was confusing to see it under the Provtool section.
Clean up the main provisioning process, and mirror it for the rebuild case.
Emphasize the current preferred practice of using `noit.local.env` for all
configuration.
> CIRC-5261 Clarify broker rebuild process

- content/circonus/on-premises/installation/installation.md
Embargoed until after the July 27 Inside release.
> CIRC-5447 API external_host attribute

- content/circonus/on-premises/jlog.md
- content/circonus/on-premises/roles-services/stratcon.md
- content/circonus/on-premises/troubleshooting.md
Intended to inform operators such that they understand how to solve
operational issues rooted in JLog.
> CIRC-5540 Centralize JLog information

- content/irondb/administration/rebuilding-nodes.md
Sub-items were insufficiently indented to render properly.
> CIRC-4307 Fix indenting to preserve step ordering

- content/circonus/on-premises/installation/getting-started.md
IRC is no longer supported for on-prem.
> Updating docs to remove references to special cases around IRC, 

- content/irondb/api/data-retrieval.md
> Typos in IRONdb read API page

- content/circonus/on-premises/installation/getting-started.md
Brian Dunavant says this isn't something we still do.
> Remove fault to postgres postgres connection from the matrix, 

- content/circonus/on-premises/datacenter-failover.md
- content/circonus/on-premises/installation/installation.md
- content/circonus/on-premises/roles-services/ca.md
- content/circonus/on-premises/roles-services/web-db.md
This is a working branch, not ready for merging yet.
> CIRC-5335 - Multi-DC updates

- content/circonus/checks/check-types/httptrap.md
Link to original feature article for full details on stream tags.
> CIRC-5810 Describe tagged metric submission

- content/circonus/on-premises/installation/installation.md
Remove obsolete things, clarify some wording here and there.
> CIRC-6238 Sample site.json cleanup

- content/circonus/on-premises/changelog/2021.md
Want the additional `data_storage` timeshard fixes.
> Late addition to 2021-02-22 Inside release

- content/circonus/search.md
* Adds documentation for the new `acknowledged` search term for alerts searching.
> CIRC-6197: Add docs for alert acknowledged search term

- content/circonus/on-premises/changelog/2021.md
Fix a mistake from the 3/22 release that updated the wrong line.
> Release notes 20210503

- content/circonus/agents/circonus-unified-agent/_index.md
- content/circonus/agents/circonus-unified-agent/basic_usage/_index.md
- content/circonus/agents/circonus-unified-agent/basic_usage/docker.md
- content/circonus/agents/circonus-unified-agent/basic_usage/freebsd.md
- content/circonus/agents/circonus-unified-agent/basic_usage/linux.md
- content/circonus/agents/circonus-unified-agent/basic_usage/macos.md
- content/circonus/agents/circonus-unified-agent/basic_usage/windows.md
- layouts/_default/list.html
Initial drop of documentation for CUA. Over time we will build this out more fully.
There are some navigation issues we'll continue to incrementally work on. That said, the base content here is significantly better than the current circumstances.
> CIRC-6581 Initial drop of documentation covering CUA

- content/circonus/agents/circonus-unified-agent/basic_usage/windows.md
Added instructions for using the Windows One-Step installer.
> CIRC-6581 Windows One Step Installer

- content/circonus/on-premises/changelog/2021.md
- content/circonus/on-premises/installation/installation.md
CIRC-6610 Add API to installation sequence
> Release notes 20210531
